### PR TITLE
Prepare for 1.0.0-alpha5 release

### PR DESCRIPTION
**Pull request by sav007**

### CODE REVIEW

**Comment by 0xcaff** [comment]
Is this released? I see it uploaded on [bintray](https://bintray.com/apollographql/android/apollo-coroutine-support), but it doesn't seem to be in [bintray's repos](https://repo.jfrog.org/artifactory/libs-release-bintray/com/apollographql/apollo/apollo-coroutine-support/1.0.0-alpha5/apollo-coroutine-support-1.0.0-alpha5.jar)?

**Comment by sav007** [comment]
Not sure where did you get that link but it's published: https://dl.bintray.com/apollographql/android/com/apollographql/apollo/apollo-coroutine-support/

**Comment by 0xcaff** [comment]
Link works now! Yay!

**Comment by 0xcaff** [comment]
I had to add

```
    maven {
        url  "https://dl.bintray.com/apollographql/android" 
    }
```

to get it to work. The readme should be updated. The latest version doesn't seem to be available on jcenter.

**Pull request merged**
