### PR TITLE
Added Apollo-LiveData-Support (#1170)

### PR DESCRIPTION
**Pull request by skydoves**
#1170

Apollo-LiveData module

- LiveDataResponse
The LiveDataResponse class maps Response to LiveDataResponse.
There are Success, Failure, UnsuccessfulResponse, Complete sealed type classes.
RxJava can handle the state of response about onNext, onError, onComplete.
But live data cannot handle and emit values about the many kinds of response.
So I think LiveData need some wrapper class about the response.

- LiveDataApollo
The LiveDataApollo class provides methods for converting ApolloCall, ApolloPrefetch and ApolloWatcher types to LiveData sources.

- AplloExtension
The ApolloExtension class provides extensions for converting ApolloCall, ApolloPrefetch and ApolloWatcher types to LiveData sources. It based on LiveDataApollo class.

### CODE REVIEW

**Comment by sideroad** [comment]
+1

**Comment by BlazerGao** [comment]
expect apollo to support livedata

**Comment by fwal** [comment]
Any plans to continue the work on this? Looks like the source repo is gone 🤔

**Comment by martinbonnin** [comment]
I'm closing this PR for now, feel free to leave a message or reopen it.

**Pull request closed without merging**
