### PR TITLE
Remove bunch of deprecated code

### PR DESCRIPTION
**Pull request by tasomaniac**

### CODE REVIEW

**Review by sav007 — APPROVED** [review]
🍂 clean up :)

**Review by martinbonnin — APPROVED** [review]

**Comment by martinbonnin** [comment]
This conflicted with https://github.com/apollographql/apollo-android/pull/2625 on `apollo-integration` being moved to Kotlin. I just pushed a merge, @tasomaniac can you double check?

**Comment by tasomaniac** [comment]
Thanks for taking care of those. I did bunch of those but my branch was too old I guess.

**Comment by martinbonnin** [comment]
The CI failed with `cancelled 13 hours ago in 6h 0m 13s`, it looks like we're getting more and more of these :-/. I just relaunched it.

**Pull request merged**
