### PR TITLE
SQLStore - use compiled sql statements, use update for merge

### PR DESCRIPTION
**Pull request by BenSchwab**
closes https://github.com/apollographql/apollo-android/issues/369

### CODE REVIEW

**Comment by digitalbuddha** [comment]
I'm terrible with sql stuff. Didn't you just remove the compile statement stuff?

**Comment by BenSchwab** [comment]
Haha me too -- it's pretty arcane stuff. I changed the compile statement to use the `insert` / `update` methods outlined here: https://developer.android.com/training/basics/data-storage/databases.html.

I _think_ the advantage is that those methods will properly cleanse the arguments for sql injection attacks.

With the compile sql using a string, I think a user could construct a malicious record key that performs sql injection.

**Comment by digitalbuddha** [comment]
Make sense thanks for explaining! I just assumed CompiledStatements == PreparedStatements.

**Comment by BenSchwab** [comment]
I think there is a difference between what I changed this too, and compiled statements. And compile statements have performance benefits. I'll go ahead and land this so SQLStore is functional, but I'll continue thinking about the optimal structure.

And yeah sqlDelight might be nice :)

**Pull request merged**
