### PR TITLE
do not try to compile java files if we don't generate any

### PR DESCRIPTION
**Pull request by martinbonnin**
Should fix https://github.com/apollographql/apollo-android/issues/1352

### CODE REVIEW

**Comment by martinbonnin** [comment]
Test added there: https://github.com/apollographql/apollo-android/blob/95b0e854eb5953d95acceabb474a8e193b9af3f3/apollo-gradle-plugin/src/test/testProject/kotlin/build.gradle

As it's using the snapshots, it will fail until new snapshosts are deployed. I'm not sure how this was handled before ?

**Comment by sav007** [comment]
Do you know why integration test fails on CI? As it a composite test and should run with the latest changes to plugin without waiting for snapshot to be published.

**Comment by martinbonnin** [comment]
Pretty sure I didn't do the composite thing. Right now it uses the snapshot plugin which is why it fails. I'll look into composite tests

**Comment by martinbonnin** [comment]
It should be good. 2 points worth noting:

* I had to move the creation of the apollo tasks to `afterEvaluate`. This might or might not have side effects but it's the only way I found to know reliably the value of apollo.generateKotlinModels and configure the java task.
* The other tests simply add the apollo-api code to the java sourceSet which defeats the value of this test (testing that the project compiles without any java file). In order to still have the api dependency, I included the snapshot so the test is run with a local plugin and a snapshot api. This might or might not be an issue...

**Comment by sav007** [comment]
I will take a look on my sample project with snapshot version if `afterEvaluate` caused any issues, it shouldn't but will check.

**Comment by alexxxdev** [comment]
> I will take a look on my sample project with snapshot version if `afterEvaluate` caused any issues, it shouldn't but will check.

@sav007 @martijnwalraven it seems
now it causes problems with `compile%name%Kotlin`
for any value of `generateKotlinModels`
project is 100% kotlin

`/build/apollo-codegen/` empty & `/build/generated/source/apollo` doesn't exist

**Comment by AllanWang** [comment]
^ For me the generated sources actually do exist, but they don't get resolved properly; gradle won't allow me to use it.

#1372

**Pull request merged**
