### PR TITLE
Update apollo-codegen last version

### PR DESCRIPTION
**Pull request by gsancho**

### CODE REVIEW

**Comment by marwanad** [comment]
Did you run `gradle updateTestIRFiles` after? This task will update our test fixtures if something changed with the new codegen version.


You'll need to have apollo-codegen globally installed, `npm install -g apollo-codegen@0.10.13` and then run `gradle apollo-compiler:updateTestIRFiles` from the project root.

**Comment by sav007** [comment]
Just checked seems new version doesn't introduce changes to generated models. We can merge this PR.

**Comment by marwanad** [comment]
We might want to bump the version number [here](https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/apollo-codegen.properties). I can do it and merge later.

**Comment by sav007** [comment]
@marwanad that version is generated by when you run updateTestIRFiles. But yeah we have to update it as well

**Pull request merged**
