### PR TITLE
[Incubating plugin] Add gradle build cache test

### PR DESCRIPTION
**Pull request by martinbonnin**
~This PR is dependent on https://github.com/apollographql/apollo-android/pull/1849. Do not merge until https://github.com/apollographql/apollo-android/pull/1849 is merged.~ 
This is ok to merge now.

Add a test to check that build cache (https://docs.gradle.org/current/userguide/build_cache.html) is working correctly with the customIdGenerators.

### CODE REVIEW

**Comment by tasomaniac** [comment]
Using a custom build cache folder is a good idea. I didn't know that this was possible. 👍 

I wonder if we can find a generic way to test if build cache is working. We could have one test without even configuring the plugin with custom props. That would be easy.

**Comment by martinbonnin** [comment]
> I wonder if we can find a generic way to test if build cache is working. We could have one test without even configuring the plugin with custom props. That would be easy.

Not sure I get it. What are custom props here? `apollo. customIdGenerator ` ? This isn't really required but the customIdGenerator triggered the discussion about build cache so I decided to add the test in this context. It can certainly be added for other tests too. Or did you want to add it systematically for all tests ?

**Comment by tasomaniac** [comment]
Sorry my comment here was just brain-storming and was out of scope of this PR. I was wondering if it would be possible to write (smoke) tests for build cache. They would run over PRs and detect any accidental build cache breakages. It is just an idea.

**Comment by martinbonnin** [comment]
We could but I don't think build cache would break a lot. While the gradle plugin has some complexity, it should be self contained enough so that it doesn't break too much?

**Comment by martinbonnin** [comment]
I'm merging this one because it's a small one and I want to open a PR to promote the incubating plugin and this would conflict. Let me know you want me to change anything.

**Comment by tasomaniac** [comment]
All good. I meant to approve it actually. 👍

**Pull request merged**
