### PR TITLE
Reorganize api-module

### PR DESCRIPTION
**Pull request by sav007**
As a prerequisite for migrating `apollo-api` module to Kotlin, unfortunately these changes are not binary compatible with previous version.

- Extract http cache related API classes to separate module `apollo-http-cache-api`
- Move several classes under `internal` package as they shouldn't have been public at first place (`JsonDataException`, `JsonEncodingException`, `InputFieldMarshaller`, `InputFieldWriter`, `ResponseFieldMapper`, `ResponseFieldMarshaller`, `ResponseReader`, `ResponseWriter`)
- Move couple classes in `apollo-api` module under `api` subpackage (`ApolloLogger`, `QueryDocumentMinifier`, `CustomTypeAdapter`, `CustomTypeValue`, `ScalarTypeAdapters`)

Part of https://github.com/apollographql/apollo-android/issues/1455

### CODE REVIEW

**Comment by martinbonnin** [comment]
Nice ! That's looking good :).

One still that still bugs me a little bit is how we use the term `api`. We have 3 usages right now:

1. for `apollo-api`, `internal` is a subpackage of `api`
2. for `apollo-gradle-plugin`, `internal` is a sibling pacakge of `api`
3. for `apollo-http-cache`, we now have two modules: `apollo-http-cache` and `apollo-http-cache-api`

I think 3. is the way to go because it will prevent to leak internal classes to consumers. Actually I wanted to do the same for the gradle plugin (See https://github.com/apollographql/apollo-android/issues/1697).
Maybe we should take this opportunity to split the `apollo-api` module in two new modules ?
* `apollo-core`
* `apollo-core-api`

But it adds a bit of complexity because it basically duplicates all modules. Also there's https://github.com/apollographql/apollo-android/pull/1784 incoming that introduces `apollo-api-core`, which I haven't had the time to dig into a lot yet. 

All in all, I'm not sure what to do with all this so feel free to merge this pull request as it's a nice reorganisation. We can always figure out things later (if things need figuring out...)

**Comment by tasomaniac** [comment]
I never worked with a big enough library to split everything into api vs implementation to completely hide internal implementation details from consumers. In smaller libraries, I tried that and found out that it's an overkill. `internal` naming in the package is a decent solution, imho.

**Comment by martinbonnin** [comment]
@tasomaniac I agree it might be overkill but should wee at least try to stay consistent ? If we're not doing it for `apollo-gradle-plugin`, then we shouldn't do it for `apollo-http-cache` ?

**Comment by tasomaniac** [comment]
Good point! Do we actually need to split the http cache into 2? What was the reason behind that?

**Comment by sav007** [comment]
Hey folks.

@martinbonnin @tasomaniac 
> Do we actually need to split the http cache into 2

We do need 2 modules because `apollo-http-cache-api` required by both `apollo-http-cache` and `apollo-runtime` and it has minimum set of supporting interfaces / classes, without them `apollo-runtime` / `apollo-http-cache` won't even compile.

You can use `apollo-runtime` without `apollo-http-cache` but you can't use it without `apollo-http-cache-api`, as it's just won't compile or crash in runtime with class not found exception. Our runtime heavily integrated with http cache supporting files.

@martinbonnin 
> Maybe we should take this opportunity to split the apollo-api module in two new modules ?
> - apollo-core
> - apollo-core-api

I was thinking of leave `apollo-api` module to be generic for each platform (basically this is what you are  suggesting `apollo-core-api`).  Then for JVM platform we are going to have `apollo-api-jvm` that will depend on `apollo-api`.

Means that we will extract everything JVM specific from our current `apollo-api` module into `apollo-api-jvm`. Convert `apollo-api` into pure Kotlin module to be used in KN.

What do you think, does it make sense?

**Comment by sav007** [comment]
Btw, should we bump version to `1.4.0-SNAPSHOT`?

**Comment by tasomaniac** [comment]
I guess we cannot keep everything under API module either since we don't have cache related stuff there.

**Comment by martinbonnin** [comment]
Hi !

> We do need 2 modules because apollo-http-cache-api required by both apollo-http-cache and apollo-runtime

Got it 👍 

> Means that we will extract everything JVM specific from our current apollo-api module into apollo-api-jvm. Convert apollo-api into pure Kotlin module to be used in KN

Sounds good. 
`apollo-api` will still contain a bunch of `internal` classes (all the ResponseReader/Writer things), which is why I would have maybe gone with the `apollo-core` naming instead. Using `apollo-api`, it's not 100% clear whether it's the API for users or for the rest of apollo-android. But again, I'm not really sure where I'm going with this so we can decide later.

> Btw, should we bump version to 1.4.0-SNAPSHOT?

Yes ! 🚀 We can always branch and cherry pick if we need to make a maintainance release

**Comment by tasomaniac** [comment]
💃

**Comment by martinbonnin** [comment]
🚀

**Pull request merged**
