### PR TITLE
Don't merge inline fragment with directives (conditions)

### PR DESCRIPTION
**Pull request by sav007**
Don't merge inline fragment with directives (conditions)  when it's defined on the same type (condition type) as field type.

Closes https://github.com/apollographql/apollo-android/issues/2351

### CODE REVIEW

**Comment by sav007** [comment]
>For users not using include, code that was working before will fail to compile. Unless it's backward compatible but I don't think it will since hero.name will become hero.asCharacter.name

There is no any breaking changes as we are going to generate absolutely the same code as was before. We do have test fixture `inline_fragment_merge_fields` that wasn't touched by this PR.

See https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/inline_fragment_merge_fields/TestOperation.graphql#L11

**Comment by martinbonnin** [comment]
Got it, I missed the part where the merge is done only if conditional directives are present. If I understand currently, the behaviour with this pull request is:

Without directives (unchanged):
```
query {
   hero {
     ... on Character {
       name
      }
   }  
}

// can be used with:
data.hero.name
```

With directives (fixed):
```
query HeroQuery($withDetails: Boolean!) {
   hero {
     ... on Character @include(if: $withDetails) {
       name
      }
   }  
}

// can be used with:
data.hero.asCharacter?.name
```

Would it make sense to always generate `asCharacter` to make the generated code more consistent?

**Comment by tasomaniac** [comment]
In the first one, `asCharacter` is not needed because we know the type is `Character` already. Making them consistent would definitely be nice if it is possible.

**Comment by sav007** [comment]
Sure we can do this, only it's going to be a breaking changes though.

**Pull request merged**
