### PR TITLE
Try moving docs under official Apollo docs

### PR DESCRIPTION
**Pull request by tasomaniac**
Moved docs under `docs` folder so that they are published into official docs website. 

Here the preview is already available: https://5dd1ddc687a3d100088593fb--apollo-android-docs.netlify.com/docs/android/

If you want to change the folder structure (that is found in `gatsby-config.js`, let me know. 

### screenshots

Files index is available on the left side.
Page index is available on the right.

image

### CODE REVIEW

**Comment by tasomaniac** [comment]
DO NOT MERGE!!

The links in README need to be updated. I'm also looking forward to get some feedback on left nav bar structure and titles etc. 

Thanks.

**Comment by digitalbuddha** [comment]
Lgtm

**Comment by tasomaniac** [comment]
After rebasing new docs had invalid links. It should all be good now.

**Comment by tasomaniac** [comment]
This is ready merge.

**Comment by tasomaniac** [comment]
Merging this since it was approved by 2 people and keeping it open just causes conflicts with new updates.

**Pull request merged**
