### PR TITLE
[Plugin] expose --schemaRelativeToProject to the command-line

### PR DESCRIPTION
**Pull request by martinbonnin**
This PR makes the option available on the command line. See https://github.com/apollographql/apollo-android/pull/2321#pullrequestreview-430412707

### CODE REVIEW

**Comment by tasomaniac** [comment]
I saw the earlier discussion in the review but I'm really not sure the benefit of this. It just adds more complexity without a big benefit. What do you think?

**Comment by martinbonnin** [comment]
No real strong opinion here. I initially left it out for this exact reason but on the other hand it doesn't cost much. @francescocervone can you detail your use case? Is there something you can achieve with `--schemaRelativeToProject` that doesn't work with `--schema`?

**Comment by francescocervone** [comment]
Before that PR, we used the `schema` option which generated the json relative to the project it was invoked.
After that PR, just by replacing `-Pcom.apollographql.apollo.schema` with `--schema`, the behavior changed. Then I saw the `schemaRelativeToProject` option and I realized. I just wondered why excluding this option.

I'll describe our use case.
We have a shell script that we invoke from outside the module that applies the Apollo plugin, so it would be helpful also having the `--schemaRelativeToProject` property.
Also, passing `-Pcom.apollographql.apollo.schemaRelativeToProject` to `downloadApolloSchema` task, doesn't seem to work.
We currently configure the `downloadApolloSchema` task in our `build.gradle` script.

**Comment by francescocervone** [comment]
It's not a big deal. You can close this PR if you believe it's too hard to maintain. As long as we are able to generate our schema, we have everything we need. This is just a small improvement.

**Comment by martinbonnin** [comment]
Would https://github.com/apollographql/apollo-android/issues/2364 work in your case? The idea is to lookup the location of `schema.json` automatically. You would only have to specify `--schema` for the initial download but after that, updates will overwrite the existing `schema.json`.

Unless there's a strong argument against, I'll also deprecate the `com.apollographql.apollo.XYZ` properties as the same functionality should be achievable with `--schema` and `--endpoint`.

**Comment by francescocervone** [comment]
@martinbonnin I hope this will not depend upon the working directory the task is invoked. In that case, what if I have two modules with two `schema.json` files?

**Comment by martinbonnin** [comment]
The automatic resolution will not depend on the working directory, just the apollo configuration in the given module.

**Comment by francescocervone** [comment]
That's perfect, then. Thanks!

**Comment by martinbonnin** [comment]
Closing in favor of https://github.com/apollographql/apollo-android/pull/2380
@francescocervone can you take a look?

**Pull request closed without merging**
