### PR TITLE
Use "provided" and "compileOnly" for annotations

### PR DESCRIPTION
**Pull request by jaredsburrows**
Closes: https://github.com/apollographql/apollo-android/issues/116

Related: https://github.com/apollographql/apollo-android/pull/117

### CODE REVIEW

**Comment by sav007** [comment]
our integration_tests_composite failed

**Comment by jaredsburrows** [comment]
@sav007 Yes. I am looking into it now.

**Comment by sav007** [comment]
Look into `gradle/composite` you probably need to update it as well

**Comment by jaredsburrows** [comment]
I still need to fix `apollo-api`, this is used by everything.

**Comment by jaredsburrows** [comment]
@sav007 What does that integration test do? What are you trying to test exactly with the module swapping?

**Comment by marwanad** [comment]
@jaredsburrows It's basically running the `apollo-integration` test classes against a locally built version of the plugin (as opposed to the maven artifact).

**Comment by jaredsburrows** [comment]
@marwanad Thanks. I need to take a look at the `.sh` script. Once I fix this, we should be able to merge.

**Comment by jaredsburrows** [comment]
I am not sure I finished this one. I didn't make "apollo-android" use
"compileOnly" yet.

**Pull request merged**
