### PR TITLE
Make IR generation workable anywhere

### PR DESCRIPTION
**Pull request by xrd**
If you run the task `./gradlew :apollo-compiler:updateTestIRFiles` from the command line, IR generation works fine.

If you run from the Android Studio gradle menu, the task fails because the working directory is mistakenly set to `apollo-compiler` (so paths look like `apollo-compiler/apollo-compiler/...` and IR fails). 

This PR makes it so that the task figures out its contextual working directory and does the right thing.

### CODE REVIEW

**Comment by xrd** [comment]
@digitalbuddha I added a few more commits to make this less platform specific. Just FYI.

**Comment by sav007** [comment]
@xrd can we merge this PR?

**Comment by xrd** [comment]
@sav007 It works for me both from AS gradle menu and the command line. I say yes.

**Comment by xrd** [comment]
@sav007 Is my comment clear? Do you need more information from me. The PR is ready to merge.

**Pull request merged**
