### PR TITLE
Suppress raw type warning in generated code

### LINKED ISSUE #1895: suppressRawTypesWarning = true doesn't work correctly
Using:

com.apollographql.apollo:apollo-gradle-plugin-incubating:1.2.2

Java 13

Gradle 6.0.1

Build.gradle contains:

apollo {
	suppressRawTypesWarning = true
}

After I regenerated the classes, only CustomType.java contains @SuppressWarnings("rawtypes"). My query class still contains the warnings. For example:

```
    @SuppressWarnings("unchecked")
    public ResponseFieldMarshaller marshaller() {
      return new ResponseFieldMarshaller() {
        @Override
        public void marshal(ResponseWriter writer) {
          writer.writeList($responseFields[0], getAllCustomers, new ResponseWriter.ListWriter() {
            @Override
            public void write(List items, ResponseWriter.ListItemWriter listItemWriter) {
              for (Object item : items) {
                listItemWriter.writeObject(((GetAllCustomer) item).marshaller());
              }
            }
          });
        }
      };
    }

```

Warns on the writer.writeList line and warns on the public void write line.

### PR DESCRIPTION
**Pull request by zhuhaow**
Fixes #1895

### CODE REVIEW

**Comment by zhuhaow** [comment]
Is there a way to generate the fixture automatically?

**Comment by tasomaniac** [comment]
@zhuhaow there is but I always forget. The failed tests should give you the name of the flag in the failure message.

**Comment by zhuhaow** [comment]
It seems like a CI bug, it succeeded in my repo

https://github.com/zhuhaow/apollo-android/runs/576432390

**Comment by tasomaniac** [comment]
Unfortunately, one Kotlin Multiplatform test is flaky. I re-run the job. Let's see now.

Thanks a lot for the contribution 🎉

**Pull request merged**
