### PR TITLE
Very minor documentation updates

### PR DESCRIPTION
**Pull request by louistsaitszho**

### CODE REVIEW

**Comment by martinbonnin** [comment]
I might have closed this one a bit too fast actually. Would'nt it make sense to have the method called `onCompilationUnit` instead of `onCompilationUnits` ?

**Comment by louistsaitszho** [comment]
@martinbonnin maybe, but `onCompilationUnits` is what the gradle plugin understands.

**Comment by martinbonnin** [comment]
What I'm saying is that maybe we should fix the plugin instead of the doc ? Having a plural `compilationUnits` with a single `CompilationUnit` parameter sounds a bit weird.

**Comment by louistsaitszho** [comment]
Sounds reasonable, but for those who are using 1.3.0 now, it would be better to have the documentation that doesn't trick them. Will have that documentation update included in that PR.

**Pull request merged**
