### PR TITLE
Use the same normalized cache for mutations and queries

### PR DESCRIPTION
**Pull request by lincolnq**
This fixes my use case (see discussion on #714), so I made this change for my branch of Apollo.

### CODE REVIEW

**Comment by sav007** [comment]
@BenSchwab @martijnwalraven @digitalbuddha do you guys remember why we have separated root for queries and mutations ?

**Comment by sav007** [comment]
We don't allow to read cache for mutations, so I guess this PR should be fine

**Comment by lincolnq** [comment]
Okay, well, I don't have time to push this forward much more, but it's a simple enough change so I guess probably okay to merge, assuming it passes all the tests (I haven't yet tried to run them).

**Comment by sav007** [comment]
New PR is up: https://github.com/apollographql/apollo-android/pull/743
Closing this one

**Pull request closed without merging**
