### PR TITLE
Build pushes only to master

### PR DESCRIPTION
**Pull request by tasomaniac**
With every pull request we are building both the branch and the PR. Building the branches is just redundant.

This PR changes so that they run only on `master` branch

### CODE REVIEW

**Comment by martinbonnin** [comment]
Does that scenario work?

1. I open a pull request to merge `featureBranch` into `master`
2. The CI will receive a `pull_request` event
3. I push more commits to `featureBranch`
4. Will the CI receive another `pull_request` event ? 

I would be tempted to say yes or the checks wouldn't be valid but I didn't find a good documentation of when `pull_request` is triggered, i.e. at pull request creation or every time it is updated.

**Comment by tasomaniac** [comment]
It is definitely every time it is updated. I can actually try it with this PR already.

Specifically on this PR, push checks did not run. Pushing a commit should trigger a build.

Also builds from forks never trigger the "push" event.

**Comment by tasomaniac** [comment]
It is definitely every time it is updated. I can actually try it with this PR already.

Specifically on this PR, push checks did not run. Pushing a commit should trigger a build.

Also builds from forks never trigger the "push" event.

**Comment by tasomaniac** [comment]
Yep, triggered

**Pull request merged**
