### PR TITLE
Include __typename field only in case of inline and regular fragments

### PR DESCRIPTION
**Pull request by sav007**
Closes https://github.com/apollographql/apollo-android/issues/1458

### CODE REVIEW

**Comment by sav007** [comment]
After working on this PR I realized that removing `__typename` field generation will break normalized cache as it totally depends on this field, any other query with inline / regular fragment won't resolve cached response as `__typename` fields is missing. Closing.

**Comment by sav007** [comment]
After giving another thought, we can guard this under configuration flag.

**Comment by ruiaraujo** [comment]
@sav007 Is there plans to finish this? If those `__typename` compresses well, the costs for the client can be significant for large queries.

With some guidance on what was missing, a contribution could be attempted for 1.3.0.

**Comment by tasomaniac** [comment]
@ruiaraujo there is definitely a contribution opportunity here. This work needs to be behind a configuration provided from Gradle plugin.

**Pull request closed without merging**
