### PR TITLE
Upload file

### PR DESCRIPTION
**Pull request by truongsinh**
Implement https://github.com/apollographql/apollo-android/issues/640 according to the spec https://github.com/jaydenseric/graphql-multipart-request-spec.

- [x] Implementation
- [x] Unit test
- [ ] Instruction

### CODE REVIEW

**Comment by truongsinh** [comment]
I see that it fails `checkstyle` but also in files not changed by this MR. Btw, do we have autofix for style?

**Comment by truongsinh** [comment]
@digitalbuddha @chalermpong can you take a look please

**Comment by RoryKelly** [comment]
@truongsinh anything i can do to help speed this along?

**Comment by truongsinh** [comment]
@RoryKelly it's usable (in a production app in my company) by using custom bintry https://bintray.com/truongsinh/android . For this MR to merge to upstream, I'm waiting for help in fixing 1 regression automated test, and for upstream author to actually review and approve this MR.
cc @digitalbuddha @chalermpong

**Comment by sav007** [comment]
Please rebase this PR.

**Comment by digitalbuddha** [comment]
is this different than the other file upload pr that was merged #1286

**Comment by sav007** [comment]
Sorry I'm not sure what is this PR is trying to address. We just recently added support for upload files. Could please elaborate more on this PR?

**Comment by digitalbuddha** [comment]
closing for now, not sure if this is needed anymore

**Comment by EngMahmoudMagdy** [comment]
> Sorry I'm not sure what is this PR is trying to address. We just recently added support for upload files. Could please elaborate more on this PR?

Please, Can you provide a working example for file uploading, Because Apollo-android documentation "file upload support" part has errors in **Upload** custom scalar type and I can't solve it after following carefully everything in README file of the repo

**Comment by chalermpong** [comment]
> > Sorry I'm not sure what is this PR is trying to address. We just recently added support for upload files. Could please elaborate more on this PR?
> 
> Please, Can you provide a working example for file uploading, Because Apollo-android documentation "file upload support" part has errors in **Upload** custom scalar type and I can't solve it after following carefully everything in README file of the repo here
> https://github.com/apollographql/apollo-android#support-file-upload

What error are you facing? The file upload support feature is available from version 1.0.1 please make sure you have the right version.

**Comment by EngMahmoudMagdy** [comment]
> > > Sorry I'm not sure what is this PR is trying to address. We just recently added support for upload files. Could please elaborate more on this PR?
> > 
> > 
> > Please, Can you provide a working example for file uploading, Because Apollo-android documentation "file upload support" part has errors in **Upload** custom scalar type and I can't solve it after following carefully everything in README file of the repo here
> > https://github.com/apollographql/apollo-android#support-file-upload
> 
> What error are you facing? The file upload support feature is available from version 1.0.1 please make sure you have the right version.

Thanks for replying, I found the problem and solve it, it was another query made a conflict with the uploading mutation, sorry for bothering.

**Comment by EngMahmoudMagdy** [comment]
@chalermpong I have another question here, please.
Where is the customTypeAdapter of Upload Scalar type ?
I can't upload the file as it is directly like  the code here: https://github.com/apollographql/apollo-android#support-file-upload 
App crashes and the exception is:

> 
    java.lang.IllegalArgumentException: Can't map GraphQL type: Upload to: class com.apollographql.apollo.api.FileUpload. Did you forget to add custom type adapter?
        at com.apollographql.apollo.response.ScalarTypeAdapters.adapterFor(ScalarTypeAdapters.java:29)
        at com.apollographql.apollo.internal.json.InputFieldJsonWriter.writeCustom(InputFieldJsonWriter.java:87)
        at com.magdy.myapplication.RegisterMutation$Variables$1.marshal(RegisterMutation.java:189)

And I am already made build.gradle change of mapping as the documentation says

**Comment by chalermpong** [comment]
> ScalarTypeAdapters.java:29

I think you using apollo-android version older than 1.0.1, right? The exception should be thrown from ScalarTypeAdapters.java: 30 (see [here](https://github.com/apollographql/apollo-android/blob/4a3bfe0204cb374c13a146d1b9334f4d8a2331d1/apollo-runtime/src/main/java/com/apollographql/apollo/response/ScalarTypeAdapters.java#L30))
Try update to version 1.0.1

**Comment by EngMahmoudMagdy** [comment]
@chalermpong Thank you so much for notifying me for this, I didn't know that the feature was added recently, so Thank you for help, my team are looking forward to getting the same feature support in iOS platform.

**Pull request closed without merging**
