### PR TITLE
Add configuration to generate Kotlin models with internal modifier

### PR DESCRIPTION
**Pull request by sav007**
Closes https://github.com/apollographql/apollo-android/issues/1605

### CODE REVIEW

**Comment by tasomaniac** [comment]
I am thinking now whether if we should segregate Kotlin only configuration extensions vs others.

**Comment by martinbonnin** [comment]
> I am thinking now whether if we should segregate Kotlin only configuration extensions vs others in the incubating plug-in

At some point I was contemplating have 2 pluginIds: `com.apollographql.apollo.java` and `com.apollographql.apollo.kotlin`. Not sure if it's really worth it or if it will bring confusion...

**Comment by tasomaniac** [comment]
2 separate plugins may mean also code duplication. I'm not sure. Somehow separation would be useful tho. Right now, it is getting confusing too. Like this internal modifier is available to Java users. They don't need it.

**Comment by martinbonnin** [comment]
> 2 separate plugins may mean also code duplication. 

Not necessarily. We can use the same jar, 2 pluginIds and reuse as much of the plugin code as we want.
* We'll know even before `Plugin.apply()` what kind of source file is going to be generated => no more need for `afterEvaluate` to setup the sourceSets
* Only expose in the gradle configuration the parameters that are useful for the targetted language.

> Somehow separation would be useful tho. Right now, it is getting confusing too

Agreed. We could do something like:

```kotlin
apollo {
    outputPackageName.set("com.example")
    kotlinOptions {
       generateAsInternal.set(true)
    }
    javaOptions {
       nullableValueType.set("annotated")
    }
}
```

> Like this internal modifier is available to Java users

It's caught at runtime at the moment with checks like this:
https://github.com/martinbonnin/apollo-android/blob/bea404bc589e298715c8aad3ea5d0675165b3181/apollo-gradle-plugin-incubating/src/main/kotlin/com/apollographql/apollo/gradle/internal/ApolloGenerateSourcesTask.kt#L123
Agreed compile time would be better.

**Pull request merged**
