### PR TITLE
Replace Moshi with generated marshaller for operation json serialization

### PR DESCRIPTION
**Pull request by sav007**
Part of #572 

Next step is to remove Moshi from SqlNormalizedCache

### CODE REVIEW

**Comment by digitalbuddha** [comment]
@sav007 should this be made configurable. I worry that most won't care about the optimization but will care about the additional methods the request parsing generates.

**Comment by sav007** [comment]
@digitalbuddha well I see your point but not sure if that won't be a messy to have it both. I fell like we already have too much configs, and it was our initial idea use generation instead of Moshi.
Plus I feel like we really won't benefit of saving couple methods here. Maybe we can later optimize it a little bit when such concern raised.

**Comment by jaredsburrows** [comment]
@digitalbuddha I completely agree. 

@sav007 In this PR, I did not see you remove the dependency from the `build.gradle`. Did you remove it in another PR?

**Comment by jaredsburrows** [comment]
Are you going to remove moshi completely from this repository? It looks like it is still used: https://github.com/apollographql/apollo-android/search?utf8=%E2%9C%93&q=moshi&type=.

**Pull request merged**
