### PR TITLE
Prepare for release v0.3.3

### PR DESCRIPTION
**Pull request by felipecsl**

### CODE REVIEW

**Comment by felipecsl** [comment]
Hmm master is already ahead?!

**Comment by BenSchwab** [comment]
bd7aead1ea33f21353f5582b9ea53b57f9669a5c was a breaking change so I bumped the snapshot version to `v0.4.0` in that commit -- hopefully, that doesn't mess up this release

**Comment by BenSchwab** [comment]
6b74c7181390272ab14b47a9a7b8030f154c9c63 is the commit we would want to tag as `v0.3.3`

**Comment by felipecsl** [comment]
Created a draft for the tagged release here https://github.com/apollographql/apollo-android/releases/tag/untagged-d5a21b67cf906ff65fcd

**Pull request merged**
